// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Train_project.Data;

#nullable disable

namespace Train_project.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241229150823_interrelationships")]
    partial class interrelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Train_project.Core.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCode"), 1L, 1);

                    b.Property<DateTime>("EmployedFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmployeeCode");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Train_project.Core.Entities.PublicInquiryEntity", b =>
                {
                    b.Property<int>("InquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InquiryId"), 1L, 1);

                    b.Property<string>("ComplainantsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplainantsPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionInquiry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool?>("StatusInquiry")
                        .HasColumnType("bit");

                    b.Property<int>("TreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("WorkerEmployeeCode")
                        .HasColumnType("int");

                    b.HasKey("InquiryId");

                    b.HasIndex("DriverId");

                    b.HasIndex("WorkerEmployeeCode");

                    b.ToTable("PublicInquiry");
                });

            modelBuilder.Entity("Train_project.Core.Entities.StationEntity", b =>
                {
                    b.Property<int>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationID"), 1L, 1);

                    b.Property<string>("LocationGPSCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPlatforms")
                        .HasColumnType("int");

                    b.Property<string>("StationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationType")
                        .HasColumnType("int");

                    b.HasKey("StationID");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("Train_project.Core.Entities.TrainEntity", b =>
                {
                    b.Property<int>("TrainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainID"), 1L, 1);

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCars")
                        .HasColumnType("int");

                    b.Property<string>("RegularRoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainLine")
                        .HasColumnType("int");

                    b.Property<bool?>("TrainStatus")
                        .HasColumnType("bit");

                    b.HasKey("TrainID");

                    b.ToTable("Train");
                });

            modelBuilder.Entity("Train_project.Core.Entities.TrainRouteEntity", b =>
                {
                    b.Property<int>("TrainRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainRouteId"), 1L, 1);

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstTrain")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastTrain")
                        .HasColumnType("datetime2");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("SubstituteDriverId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("TrainRouteId");

                    b.HasIndex("DriverId");

                    b.HasIndex("StationId");

                    b.HasIndex("SubstituteDriverId");

                    b.HasIndex("TrainId");

                    b.ToTable("TrainRoute");
                });

            modelBuilder.Entity("Train_project.Core.Entities.PublicInquiryEntity", b =>
                {
                    b.HasOne("Train_project.Core.Entities.EmployeeEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Train_project.Core.Entities.EmployeeEntity", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerEmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Train_project.Core.Entities.TrainRouteEntity", b =>
                {
                    b.HasOne("Train_project.Core.Entities.EmployeeEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Train_project.Core.Entities.StationEntity", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Train_project.Core.Entities.EmployeeEntity", "SubstituteDriver")
                        .WithMany()
                        .HasForeignKey("SubstituteDriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Train_project.Core.Entities.TrainEntity", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Station");

                    b.Navigation("SubstituteDriver");

                    b.Navigation("Train");
                });
#pragma warning restore 612, 618
        }
    }
}
